### ISSUE TITLE
Downloading Binary files using Get-Blob

### ISSUE THREAD

**Issue by samjudson** [Kevin-Bronsdijk/JAABAW-Just-Another-Azure-Blob-API-Wrapper#1]
Hi

Just to say I've had loads of issues trying to download binary files (zip files specifically) using the Get-Blob function.

I think the reason was the use of the StreamReader, so I ended up passing in a -FilePath parameter which if specified just copies the stream to a file.

Would you be interested in seeing a pull request for this?

**Comment by Kevin-Bronsdijk** [comment]
@samjudson Hi and sorry for the delay in my response :) I’ve had GitHub notification issues in the past and therefore not aware of your comment. 

This was just a “play” project adding missing rest API calls. At the moment of writing this update I’m mostly using the .net SDK within my PowerShell scripts.

**Comment by samjudson** [comment]
Hi

Thanks, I have no idea what I originally wrote and have probably lost the modification now ;)

I'll look at the SDK and see if its any use for my needs.

Sam
